version: "3.9"
services:
  log_server:
    build: ./server
    networks:
      - custom
    ports:
      - '8080:8080'
    links:
      - log_postgresql
    
  log_postgresql:
    image: "postgres:latest"
    networks:
      - custom
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: log_base
    ports:
      - '54321:5432'
    expose:
      - '54321'
    container_name: log_postgresql_app

networks:
  custom:
